### ISSUE TITLE
How to distinguish between incremental and full on remote side

### ISSUE THREAD

**Issue by istvano** [searchisko/elasticsearch-river-remote#60]
Hi,

Thanks again for the delete feature it is great. #59 although I have a question.
I have the following scenario where I would like to ask your opinion what is the best way to implement it.

a, full update -> I do not wish to send deleted elements from the remote to the river as they have been deleted
b, partial update -> I must send elements to ES which are marked deleted.

q1, is there a way I can distinguish the request coming from the river to the remote site to see if it is a incremental update request or if it is a full reindex request ?

q2, In case of full reindex when I am sending back elements which are marked deleted already using (emote_field_deleted)  is the remote indexer pushing them to ES ? At the moment the document gets indexed which is fair. Although since at the moment I do not know how to see on the remote side if I need to send the deleted item I am sending as the incremental update request needs to see the deleted document.

is it possible to add an additional parameter to the url to show if this is full or incremental request.
https://system.org/rest/document?docSpace={space}&docUpdatedAfter={updatedAfter}&request={requestType}

where requestType is either incremental or full. What do you think ?

Thanks in advance,

**Comment by velias** [comment]
Ad1) it is a good idea to make it possible to pass indexing type into URL, will do it

Ad2) I strongly believe that document is not stored in ES index if it contains deleted flag during full update

**Comment by velias** [comment]
URL parameter is `{indexingType}` with values `full` or `inc`, see doc.

**Comment by istvano** [comment]
Hi,

great thanks a lot for this. I am not sure why but deleted elements ended up in my ES maybe mapping error on my part I will double check. This is why I though I would need to know if it was a full or partial.

I will check it. and thanks for the UPDATE ! It is great. I hope it is an addition for others as well!

**Comment by istvano** [comment]
Hi,

I do not seem to see the 1.6.3 on the jboss repo. Do you know when it can be expected to be there ?

https://repository.jboss.org/nexus/content/groups/public-jboss/org/jboss/elasticsearch/elasticsearch-river-remote/

thanks

**Comment by velias** [comment]
Hi, it is available there now
