### ISSUE TITLE
how to disable initial full update

### ISSUE THREAD

**Issue by istvano** [searchisko/elasticsearch-river-remote#61]
Hi,

I am wondering if there is a way to disable initial full update during the creation of a river ?

I tried to do ->

        "getDocsResFieldDocuments"  : "documents",
		"getDocsResFieldTotalcount" : "total",
        "timeout"               : "120s",
        "indexUpdatePeriod"     : "1h",
        "indexFullUpdatePeriod" : "0",
	"spacesIndexed"			: "space",
        "maxIndexingThreads"    : 2

Although it seems this index also runs at startup time and does a full update.

Thanks for any suggestions in advance,

**Comment by velias** [comment]
Hi,

incremental update must continue from some point last update finished at, so it means full update must be done initially if this point is not defined. This point is update timestamp of last updated item during last run. This timestamp is passed to the list documents URL as `updatedAfter` param during next incremental update run.  

River stores this timestamp into JSON document inside river's index (`/_river/your_river_name/`), separately for each indexed space. So you should be able to use elasticsearch REST API to create this file before you start indexer first time. 
Document name should be `_lastIndexedDocumentUpdateDate_space` if your space name is `space`. Document content should be (timestamp in ISO format):

````
{
  "value" : "2005-01-26T00:00:00Z"
}
````
But try to look you elasticsearch instance if this file name and content is correct ;-)

**Comment by istvano** [comment]
thanks! this is great
