### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by nokru** [searchisko/elasticsearch-river-remote#77]
there is a typo in the install string:
bin/plugin -url https://repository.jboss.org/nexus/content/groups/public-jboss/org/jboss/elasticsearch/elasticsearch-river-remote/1.6.4/elasticsearch-river-remote-1.6.5.zip -install elasticsearch-river-remote

i guess it should be
bin/plugin -url https://repository.jboss.org/nexus/content/groups/public-jboss/org/jboss/elasticsearch/elasticsearch-river-remote/1.6.5/elasticsearch-river-remote-1.6.5.zip -install elasticsearch-river-remote

so the directory seems to be wrong

beside that - i love the plugin - keep on the good work :)

**Comment by unibrew** [comment]
Thanks! I fixed this as part of 1.6.6 release.
